typography_spectrum: 0.49774
color:
  brandColors:
    - '#cee9fe'
    - '#819cb7'
    - '#0f1217'
    - '#de4358'
    - '#5e5d62'
  brandStrength: 0.25
  lightness: 0.37354895868338645
  saturation: 0.039017612813040614
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75669
analytics:
  google: null
  facebook: null
  twitter: null
name: autenrieth sailing
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Philipp & Julian Autenrieth
purpose: []
