layout_spectrum: 0.75669
typography_spectrum: 0.49428919865749776
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.06665998860262334
  lightness: 0.8425353937782347
  saturation: 0.8215627186000347
  rhythmicContrast: 0.7505543462466449
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/09e5e220-ae0a-42e1-baac-adc9e83f3434.png
  type: Fanpage
  appId: 'https://www.facebook.com/dieschautenrieth/'
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2ffe47e2-0297-4faf-916c-b9d5894cb9dc.jpg
name: autenrieth sailing
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Team
    id: a51eeae8-f367-4c93-a5cb-cba1f3bffe00
    type: content
  - name: News
    id: 24ae3a81-3b3d-4a1d-ad48-0d70f57fc24b
    type: content
favicon: null
title: autenrieth-sailing
description: Philipp & Julian Autenrieth
purpose: []
