name: autenrieth sailing
favicon: null
layout_spectrum: 0.25167
typography_spectrum: 0.49774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cee9fe'
    - '#819cb7'
    - '#0f1217'
    - '#de4358'
    - '#5e5d62'
  brandStrength: 0.25
  lightness: 0.37354895868338645
  saturation: 0.039017612813040614
  rhythmicContrast: 0.25
purpose: []
