name: autenrieth sailing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1919'
    - '#d7d7d7'
    - '#959595'
    - '#504f4f'
  brandStrength: 0.25
  lightness: 0.37354895868338645
  saturation: 0.039017612813040614
  rhythmicContrast: 0.25
purpose: []
